# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyType', models.CharField(max_length=250)),
                ('registeredName', models.CharField(max_length=250)),
                ('companyName', models.CharField(max_length=250)),
                ('dateFiled', models.DateTimeField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipCode', models.IntegerField()),
            ],
        ),
    ]
